---
# tasks file for deploy_es
#- name: Download es v7.10.2 and shasum
#  ansible.builtin.get_url:
#   url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.2-linux-x86_64.tar.gz
#   dest: /tmp/elasticsearch-7.10.2-linux-x86_64.tar.gz

- name: Check that the directory /tmp/{{ ansible_ssh_user }}/elasticsearch-7.10.2 exists
  stat:
    path: /tmp/{{ ansible_ssh_user }}/elasticsearch-7.10.2
  register: stat_result

- name: ensure /tmp/{{ ansible_ssh_user }}/ directory exists
  file:
    path: /tmp/{{ ansible_ssh_user }}/
    state: directory
- name: Extract archive
  ansible.builtin.unarchive:
   src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.10.2-linux-x86_64.tar.gz
   dest: /tmp/{{ ansible_ssh_user }}/
   remote_src: yes
  when: stat_result.stat.exists == False 

- name: Get neighbors IP
  vars:
   neighbors_ip: []
  set_fact:
   neighbors_ip: "{{ neighbors_ip + [hostvars[neighbor].ip] }}"
  when:
   - hostvars[neighbor].elastic == true 
  loop: "{{ groups['tpE']}}"
  loop_control:
   loop_var: neighbor 

- name: Get master nodes
  vars:
   masters: []
  set_fact: 
   masters: "{{ masters + [hostvars[neighbor].inventory_hostname_short]}}"
  when:
   - hostvars[neighbor].master == true 
   - hostvars[neighbor].elastic == true 
  loop: "{{ groups['tpE'] }}"
  loop_control:
   loop_var: neighbor

- name: Generate config file on remote host
  vars:
    neighbors_ip: "{{ neighbors_ip | difference ([ip]) }}" 
  template:
   src: templates/config_file.j2
   dest: "/tmp/{{ ansible_ssh_user }}/elasticsearch-7.10.2/config/{{ config_file_name }}.yml"

- name: Create directory for ES logs 
  ansible.builtin.file:
   path: "{{ path_log }}"
   state: directory 

- name: Create directory for ES data 
  ansible.builtin.file:
   path: "{{ path_data }}"
   state: directory 
   
- name: kill pid elastichsearch
  ansible.builtin.shell: pkill -f elasticsearch
  ignore_errors: yes

- name: Run elastichsearch 
  ansible.builtin.shell: nohup /tmp/{{ ansible_ssh_user }}/elasticsearch-7.10.2/bin/elasticsearch -d &

